### ISSUE TITLE
Possible improvements for pacman_wp2_grasp_db

### ISSUE THREAD

**Issue by Tabjones** [CentroEPiaggio/unipi-grasp-datasets#1]
## TODO list  /  suggestions to improve scenario1 data quality and procedure
- [ ] 1. Replace flexiforce glove with the new IMU glove. (more accurate joint positions)
- [x] 2. Crop/downsample pointcloud, so that its stream frequency can be increased.
- [x] 3. Create and add object meshes to the visualization, this goes alongside with database creation for pose estimation.
- [x] 4. Possibly add an RGB video stream of recordings, also to be taken from Asus. The stream frequency as to be decided, according to output bagfile size and point 2.
- [ ] 5. First extrinsic calibration (Asus-PhaseSpace) could be improved further:
  - [ ] By increasing the size of the calibrator object and consequently the marker. This because Asus can't track AR marker unless put quite near the camera (less than a meter).
  - [ ] By filtering PhaseSpace transformations and AR transformations with a low pass, this was already partially done by me, but right now it's not working as expected so i'm putting it here.
- [ ] 6. Also second extrinsic calibration (Object-Star) could be improved with the same filter of point 5.
- [x] 7. Asus Intrinsic calibration should also be performed and used, this could improve pointcloud quality and consequently pose estimation performed during second extrinsic calibration. However this would arise the need of a new pose estimation database, thus if we decide to perform this, we should do it as first thing, so that points 3, 4 and 6 can benefit from this.

**Comment by carlosjoserg** [comment]
Good initiative, all scenarios will benefit from some of the points you propose. So I'm assigning you to follow up this issue. My comments on your points (I added checkboxes so you can follow your ToDo list):
- [ ] 1. I would create another scenario for that. Besides the IMU glove package has to be ROS-fied similarly to the Flexiforce glove.
- [ ] 2. Agree.
- [ ] 3. You need to generate the meshes first, otherwise it is an useless effort to include visualization at this moment.
- [ ] 4. Agree, this should be easy.
- [ ] 5. Ok, also [intrinsic calibration](http://wiki.ros.org/openni_launch/Tutorials/IntrinsicCalibration) would be advised. I leave that to you to decide. 5.2 It is the EKF implementation that needs to be improved in the [PoseTrackingFilter class](https://github.com/CentroEPiaggio/phase-space/blob/master/src/PoseTrackingFilter.cpp), preferably using [BFL](http://www.orocos.org/bfl).
- [ ] 6. Sure, but you must have object tracking within your pose estimation as we discussed sometime ago for that.
- [ ] 7. I already answered in 5. Totally agreed that if you decide to do it, it is to be done before generating the database, I already told you.
